// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderFlow.Inventory.Infrastructure.Persistence;

#nullable disable

namespace OrderFlow.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orderflow_inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderFlow.Inventory.Domain.Entity.StockItem", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_reserved");

                    b.HasKey("Sku");

                    b.ToTable("stock_items", "orderflow_inventory", t =>
                        {
                            t.HasCheckConstraint("ck_stock_on_hand_non_nagative", "quantity_on_hand >= 0");

                            t.HasCheckConstraint("ck_stock_reserved_non_nagative", "quantity_reserved >= 0");

                            t.HasCheckConstraint("ck_stock_reserved_not_exceed_on_hanh", "quantity_reserved <= quantity_on_hand");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
